# Commong parameters used across global and local costmap
  footprint: [[-0.32, -0.28], [-0.32, 0.28], [0.32, 0.28], [0.32, -0.28]]

  obstacle_range: 5.0
  raytrace_range: 6.0


# Static Layer
  static:
    map_topic: /map
    subscribe_to_updates: true

# Obstacle Layer
  obstacles:
    observation_sources: laser
    point_cloud_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#Inflation Layer
  inflation:
    inflation_radius: 1.75
    cost_scaling: 2.58
