  DWAPlannerROS: 
    acc_lim_theta: 10.0
    acc_lim_x: 8.0

    max_vel_x: 1.8
    max_vel_theta: 2.0

    acc_lim_y: 0.0
    acc_lim_trans: 0.1
    angular_sim_granularity: 0.1
    forward_point_distance: 0.325
    goal_distance_bias: 9.0
    holonomic_robot: false
    latch_xy_goal_tolerance: true
    max_scaling_factor: 0.2
    max_vel_trans: 0.55
    max_vel_y: 0.0
    min_vel_theta: 0.2
    min_vel_trans: 0.0
    min_vel_x: 0.0
    min_vel_y: 0.0
    occdist_scale: 0.01
    oscillation_reset_angle: 0.2
    oscillation_reset_dist: 0.05
    path_distance_bias: 5.0
    prune_plan: true
    restore_defaults: false
    theta_stopped_vel: 0.1
    scaling_speed: 0.25
    sim_granularity: 0.025
    sim_time: 1.7
    stop_time_buffer: 0.2
    trans_stopped_vel: 0.0
    use_dwa: true
    vth_samples: 20
    vx_samples: 3
    vy_samples: 10
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.1
    
