global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0
  rolling_window: false
  width: 400.0
  height: 400.0
  origin_x: -200.0
  origin_y: -200.0
  resolution: 0.05

  

