recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]

clearing_rotation_allowed: true

clearing_rotation_allowed: true
controller_frequency: 20.0
planner_frequency: 1.0
planner_patience: 5.0
controller_patience: 15
