
GlobalPlanner:
  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
  publish_potential: false
  use_dijkstra: false







DWAPlannerROS:
  # Translational limits
  min_vel_x: 0.0
  max_vel_x: 1.0
  min_vel_trans: 0.0
  max_vel_trans: 1.0
  acc_lim_x: 2.0 
  # Strafing limits
  holonomic_robot: false
  min_vel_y: 0.0
  max_vel_y: 0.0
  acc_lim_y: 0.0
  # Angular limits
  min_vel_theta: 0.0   
  max_vel_theta: 1.0
  acc_lim_th: 2.0
  # Parameters
  use_dwa: true
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 9.0
  max_scaling_factor: 0.2
  occdist_scale: 0.01
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 5.0
  prune_plan: true
  restore_defaults: false
  trans_stopped_vel: 0.0
  theta_stopped_vel: 0.1
  scaling_speed: 0.25
  sim_time: 1.7
  stop_time_buffer: 0.2
  vth_samples: 20
  vx_samples: 3
  vy_samples: 10
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.1
    
