
GlobalPlanner:
  old_navfn_behavior: false 
  use_quadratic: true
  use_dijkstra: false
  use_grid_path: false
  allow_unknown: true  

  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
  publish_potential: true







DWAPlannerROS:
  use_dwa: true
  # Translational limits
  min_vel_x: 0.0
  max_vel_x: 1.0
  min_vel_trans: 0.1 
  max_vel_trans: 1.0
  acc_lim_x: 2.0 
  # Strafing limits
  holonomic_robot: false
  min_vel_y: 0.0
  max_vel_y: 0.0
  acc_lim_y: 0.0
  # Angular limits
  min_vel_theta: 0.0   
  max_vel_theta: 1.0
  acc_lim_th: 2.0
  # Trajectory Scoring
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  # Oscillation
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  # Global Plan
  prune_plan: true
  # Forward Simulation 
  sim_granularity: 0.025
  sim_time: 2.5
  vth_samples: 20.0
  vx_samples: 10.0
  vy_samples: 1  
  # Goal Tolerance
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
    
